### ISSUE TITLE
PHP Inbuilt Server doesn't hit breakpoints

### ISSUE THREAD

**Issue by g105b** [michal-kocarek/PhpOnWindows#10]
When using the inbuilt server option from PHP Storm, I can't hit breakpoints in my code.

![image](https://user-images.githubusercontent.com/358014/34875564-aa7c9932-f795-11e7-8e9c-dd4906289e13.png)

This works if I switch PHPStorm to use the native Windows PHP version, but then I have all the weirdness of running PHP in Windows, which is why I found your great project.

**Comment by ruslan-pelepets** [comment]
Are you using Windows Subsystem for Linux - WSL? If yes you should use webserver in WSL apache, nginx etc. In that case configure debug in PHPStorm as for remote server as WSL acts as virtual machine (almost).

If you try to debug console or unit tests try my fork https://github.com/ruslan-pelepets/PhpOnWindows as it has improvements.

**Comment by g105b** [comment]
Yes I am using WSL, but I can use the inbuilt server when using PHP.exe or running PHP in a virtual machine, so I expected the same behaviour through this functionality.

**Comment by g105b** [comment]
A lot has changed since opening this issue - closing now to tidy up.
