### ISSUE TITLE
How to debug this project

### ISSUE THREAD

**Issue by jkroepke** [michal-kocarek/PhpOnWindows#2]
Hi!

thanks for providing stuff like this. I have problems to runs your script with my IDE.

[https://i.imgur.com/dPNSYsd.png](https://i.imgur.com/dPNSYsd.png)

Whats wrong? How to enable a file based log?

**Comment by jkroepke** [comment]
Using fopen('log') instead STDERR to get some logs:

```
[.] Testing PHP configuration in IDE? Disable logging first!
[.] Bash path: C:\WINDOWS\System32\bash.exe
[.] CWD: C:\Program Files\Java\jdk1.8.0_121\jre\bin
[.] ENV: 
[.] Input arguments: -dxdebug.remote_enable=0 C:\Users\jan\AppData\Local\Temp\ide-phpinfo.php
[.] Linux arguments: -dxdebug.remote_enable=0 /mnt/c/Users/jan/AppData/Local/Temp/ide-phpinfo.php
[.] Linux command: php -dxdebug.remote_enable=0 /mnt/c/Users/jan/AppData/Local/Temp/ide-phpinfo.php
[.] Windows command: C:\WINDOWS\System32\bash.exe -c "php -dxdebug.remote_enable=0 /mnt/c/Users/jan/AppData/Local/Temp/ide-phpinfo.php"
```

Running the windows command via shell looks great.

**Comment by alexlcdee** [comment]
Have the same issue.
Running script with IDE always failed.

When I modified script to write all output (STDERR and STDOUT) to files, I've got the following result: http://c2n.me/3IrXI2t

Setting up PHPUnit shows this text every time: http://c2n.me/3IrY6Fj

Debug output from PhpStorm and cmd: http://c2n.me/3Is5kP8

What configuration you've used? PHP version, architecture, thread safety, IDE version etc.

**Comment by KatoPue** [comment]
Same Problem here.
cmd works, bash works, PhpStorm Terminal works, PhpStorm Console Tools does not work.

**Comment by KatoPue** [comment]
With the current Windows 10 Creators update, everything is working properly ^(^.^)^

**Comment by jkroepke** [comment]
Yeah, I will close it.
