### ISSUE TITLE
phpunit does not get called properly

### ISSUE THREAD

**Issue by Vassyli** [michal-kocarek/PhpOnWindows#3]
I'm currently trying to set up PhpStorm with Bash on Windows and PhpOnWindows which, at least for running basic commands, works great.

However, phpunit doesn't seem to get called properly - it exits simply with a `Could not open input file` error due to php-cli not finding the correct file.

```
bash.exe -c "php C:/Users/sauterb/bin/lotgd/core/vendor/phpunit/phpunit/phpunit --configuration C:\Users\sauterb\bin\lotgd\core\phpunit.xml --teamcity"
Could not open input file: C:/Users/sauterb/bin/lotgd/core/vendor/phpunit/phpunit/phpunit 
```

Obviously, this is due to the windows file path being in "unix style" using slashes instead of "windows style" with backslashes, thus the conversion seems to fail.

**Comment by michal-kocarek** [comment]
Thank you for good spot, @Vassyli! I merged the commit, am closing the issue...
